### ISSUE TITLE
Postrun fails if dist directory is missing

### ISSUE THREAD

**Issue by darkstar42** [vision-it/postrun#5]
Inside a Vagrant environment, postrun execution fails if the _dist_ directory is not available and the first module to be deployed is symlinked from the _/opt/puppet/modules/_ directory

`root@cfg01:/etc/puppetlabs/code/environments/production# /etc/puppetlabs/r10k/postrun/postrun.py -v
2017-01-22 17:39:45,881 [WARNING]: No module configuration for vrt, use default
2017-01-22 17:39:45,885 [DEBUG]: Deploying local roles
Traceback (most recent call last):
  File "/etc/puppetlabs/r10k/postrun/postrun.py", line 300, in <module>
    main(args, is_vagrant, location)
  File "/etc/puppetlabs/r10k/postrun/postrun.py", line 286, in main
    deploy_modules_vagrant(dir_path=dist_dir, modules=modules, environment=env, logger=log)
  File "/etc/puppetlabs/r10k/postrun/postrun.py", line 234, in deploy_modules_vagrant
    os.symlink(src, dst)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/puppet/modules/roles' -> '/etc/puppetlabs/code/environments/production/dist/roles'`

-> ensure _dist_ directory for every environment

**Comment by martialblog** [comment]
This should do it: https://github.com/vision-it/postrun/commit/8f24907dcb884a4a57f058c0263a1fbdcdb2902d

Needs to be tested in Vagrant.

**Comment by martialblog** [comment]
Merged
